const MOODY_BLUE = '#737CCF';
const LINK_WATER = '#E1E5F8';
const PERSIAN_BLUE = '#2218A7';
const SPINDLE = '#BBC4EB';
const GOLD = '#ffcf40';

export { MOODY_BLUE, LINK_WATER, PERSIAN_BLUE, SPINDLE, GOLD };
